### ISSUE TITLE
How to use FloatingIP IP address somewhere else in a model?

### ISSUE THREAD

**Issue by n-pochet** [inmanta/openstack#17]
Hi,

I would like to know if it is possible to retrieve the IP address of an `openstack::FloatingIP` that was previously created in the model.
I didn't find in the attributes of  `openstack::FloatingIP` (or in the implementation) something about IP address.
I would like to do something like:
```
fip = openstack::FloatingIP(all the needed params)
do something with fip.address
```
Is it possible?
Thank you!

**Comment by bartv** [comment]
Yes, something like this:
```
fip = openstack::FloatingIP(provider=provider, project=project, external_network=uplink,
                            port=host.vm.eth0_port)
public_ip = std::getfact(fip, "ip_address")
```
This is the current way of doing this, however I have a currently a change ready that populates .address for you or if you set it, force that floating ip.

**Comment by bartv** [comment]
Just pushed the change (merged the allow address pair stuff as well)

**Comment by n-pochet** [comment]
Thank you for the information!
